# Generated by Django 3.1.1 on 2021-08-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.DateField()),
                ('qty', models.FloatField()),
                ('rate', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('M', 'Metre')], default='KG', max_length=2)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_qty', models.FloatField()),
                ('net_qty', models.FloatField()),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('M', 'Metre')], default='KG', max_length=2)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
                ('transaction_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionitemdetail')),
            ],
        ),
    ]
