# Generated by Django 3.1.1 on 2021-08-11 12:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_inventory_transactionitemdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitemdetail',
            name='required_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
