# Generated by Django 3.1.1 on 2021-08-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210811_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
