# Generated by Django 3.1.1 on 2021-08-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210811_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='transaction_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactionitemdetail'),
        ),
    ]
